# Generated by Django 4.2 on 2023-04-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('isPublic', models.BooleanField()),
                ('isStudent', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
            ],
        ),
    ]
